In [12]:
import numpy as np

a = np.array([[0,1], [2,3], [4,5]])
b = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#aとbを計算する
np.dot(a, b)

#計算結果を代入
result = np.dot(a,b)

#計算結果を出力
print(result)

#最大値を知る
result.max()

#最大値を代入
max_number = result.max()

#最大値を出力
print(max_number)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
